# Copyright 2018 Robin Weiss (http://www.gerdi-project.de)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-frontend
  labels:
    app: bookmark-frontend
    scs: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-frontend
  template:
    metadata:
      labels:
        scs: frontend
        app: bookmark-frontend
    spec:
      containers:
        - name: bookmark-frontend
          image: docker-registry.gerdi.research.lrz.de:5043/frontend/bookmark:0.4.0-test8
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "0"
              memory: "0"
            limits:
              cpu: "1"
              memory: "1Gi"
      imagePullSecrets:
        - name: lrz-docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bookmark-frontend
  labels:
    run: bookmark-frontend
    scs: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: bookmark-frontend
