# Copyright 2018 Nelson Tavares de Sousa ntd@informatik.uni-kiel.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
spec:
  replicas: 3
  serviceName: elasticsearch-data-service
  selector:
    matchLabels:
      app: elasticsearch-data
  template:
    metadata:
      labels:
        service: search
        app: elasticsearch-data
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - elasticsearch-data
              topologyKey: kubernetes.io/hostname
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
          env:
            - name: http.max_content_length
              value: 100mb
            - name: ES_JAVA_OPTS
              value: -Xms2048m -Xmx2048m
            - name: bootstrap.memory_lock # Swap is disabled on K8S
              value: 'false'
            - name: cluster.name
              value: gerdi-cluster
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: http.host
              value: 0.0.0.0
            - name: node.data
              value: 'true'
            - name: node.ingest
              value: 'true'
            - name: node.master
              value: 'false'
            - name: node.ml
              value: 'false'
            - name: transport.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.graph.enabled
              value: 'false'
            - name: xpack.ml.enabled
              value: 'false'
            - name: xpack.monitoring.enabled # For Kibana
              value: 'true'
            - name: xpack.watcher.enabled
              value: 'false'
            - name: discovery.zen.minimum_master_nodes # See elasticsearch-master deployment
              value: '1'
            - name: discovery.zen.ping.unicast.hosts
              value: elasticsearch-master.default.svc.cluster.local
          volumeMounts:
            - name: elasticsearch-data-dir
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data-dir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
spec:
  replicas: 1 # Do not increase this! See env vars below.
  serviceName: elasticsearch-master-service
  selector:
    matchLabels:
      app: elasticsearch-master
  template:
    metadata:
      labels:
        service: search
        app: elasticsearch-master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - elasticsearch-master
              topologyKey: kubernetes.io/hostname
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
          env:
            - name: http.max_content_length
              value: 100mb
            - name: ES_JAVA_OPTS
              value: -Xms2048m -Xmx2048m
            - name: bootstrap.memory_lock # Swap is disabled on K8S
              value: 'false'
            - name: cluster.name
              value: gerdi-cluster
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: http.host
              value: 0.0.0.0
            - name: node.data
              value: 'false'
            - name: node.ingest
              value: 'false'
            - name: node.master
              value: 'true'
            - name: node.ml
              value: 'false'
            - name: transport.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.graph.enabled
              value: 'false'
            - name: xpack.ml.enabled
              value: 'false'
            - name: xpack.monitoring.enabled # For Kibana
              value: 'true'
            - name: xpack.watcher.enabled
              value: 'false'
            - name: discovery.zen.minimum_master_nodes # Must be above half of the number of master nodes -> (spec.replicas / 2) + 1
              value: '1'
            - name: discovery.zen.ping.unicast.hosts
              value: elasticsearch-master.default.svc.cluster.local
          volumeMounts:
            - name: elasticsearch-master-dir
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master-dir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
spec:
  ports:
    - port: 9200
      protocol: TCP
  selector:
    service: search
    app: elasticsearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
spec:
  ports:
    - name: rest
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: nodes
      port: 9300
      targetPort: 9300
      protocol: TCP
  selector:
    service: search
    app: elasticsearch-master
