---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-data
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: search
        app: elasticsearch-data
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"] # Maybe this is feasible without initContainers?
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
          securityContext:
             privileged: true
             capabilities:
               add:
                 - IPC_LOCK
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: 1Gi
          env:
            - name: http.max_content_length
              value: 100mb
            - name: ES_JAVA_OPTS
              value : -Xms512m -Xmx512m
            - name: bootstrap.memory_lock # Swap is disabled on K8S
              value: 'false'
            - name: cluster.name
              value: gerdi-cluster
            - name : http.host
              value: 0.0.0.0
            - name: node.data
              value: 'true'
            - name: node.ingest
              value: 'true'
            - name: node.master
              value: 'false'
            - name: node.ml
              value: 'false'
            - name: transport.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.graph.enabled
              value: 'false'
            - name: xpack.ml.enabled
              value: 'false'
            - name: xpack.monitoring.enabled # For Kibana
              value: 'true'
            - name: xpack.watcher.enabled
              value: 'false'
            - name: discovery.zen.minimum_master_nodes # See elasticsearch-master deployment
              value: '2'
            - name: discovery.zen.ping.unicast.hosts
              value: elasticsearch-master.default.svc.cluster.local
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-master
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: search
        app: elasticsearch-master
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"] # Maybe this is feasible without initContainers?
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
          securityContext:
             privileged: true
             capabilities:
               add:
                 - IPC_LOCK
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            requests:
              memory: 1Gi
          env:
            - name: http.max_content_length
              value: 100mb
            - name: ES_JAVA_OPTS
              value : -Xms512m -Xmx512m
            - name: bootstrap.memory_lock # Swap is disabled on K8S
              value: 'false'
            - name: cluster.name
              value: gerdi-cluster
            - name : http.host
              value: 0.0.0.0
            - name: node.data
              value: 'false'
            - name: node.ingest
              value: 'false'
            - name: node.master
              value: 'true'
            - name: node.ml
              value: 'false'
            - name: transport.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.graph.enabled
              value: 'false'
            - name: xpack.ml.enabled
              value: 'false'
            - name: xpack.monitoring.enabled # For Kibana
              value: 'true'
            - name: xpack.watcher.enabled
              value: 'false'
            - name: discovery.zen.minimum_master_nodes # Must be above half of the number of master nodes -> (spec.replicas / 2) + 1
              value: '2'
            - name: discovery.zen.ping.unicast.hosts
              value: elasticsearch-master.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
spec:
  clusterIP: 10.222.21.10
  ports:
  - port: 9200
    protocol: TCP
  selector:
    service: search
    app: elasticsearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
spec:
  ports:
  - name: rest
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: nodes
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    service: search
    app: elasticsearch-master
