---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  clusterIP: 10.222.21.210
  ports:
  - port: 9092
    name: client
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: "wurstmeister/kafka:2.11-2.0.0"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zk-cs.default.svc.cluster.local:2181
          - name: KAFKA_LISTENERS
            value: INSIDE://:9092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INSIDE
        ports:
        - containerPort: 2181
          name: client
      volumes:
        - name: datadir
          hostPath:
            path: /mnt/nfs/test/ops/kafka
            type: Directory
