# Copyright 2018 Nelson Tavares de Sousa ntd@informatik.uni-kiel.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        service: common
        app: zookeeper-1
    spec:
      containers:
        - name: zk
          image: zookeeper:3.4.13
          ports:
            - name: client
              containerPort: 2181
            - name: server
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: server.1=0.0.0.0:2888:3888 server.2=zk-hs-2.default.svc.cluster.local:2888:3888 server.3=zk-hs-3.default.svc.cluster.local:2888:3888
---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs-1
  labels:
    app: zk
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs-1
  labels:
    app: zk
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper-1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-2
  template:
    metadata:
      labels:
        service: common
        app: zookeeper-2
    spec:
      containers:
        - name: zk
          image: zookeeper:3.4.13
          ports:
            - name: client
              containerPort: 2181
            - name: server
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: ZOO_MY_ID
              value: "2"
            - name: ZOO_SERVERS
              value: server.1=zk-hs-1.default.svc.cluster.local:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zk-hs-3.default.svc.cluster.local:2888:3888
---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs-2
  labels:
    app: zk
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    app: zookeeper-2
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs-2
  labels:
    app: zk
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper-2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-3
  template:
    metadata:
      labels:
        service: common
        app: zookeeper-3
    spec:
      containers:
        - name: zk
          image: zookeeper:3.4.13
          ports:
            - name: client
              containerPort: 2181
            - name: server
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: ZOO_MY_ID
              value: "3"
            - name: ZOO_SERVERS
              value: server.1=zk-hs-1.default.svc.cluster.local:2888:3888 server.2=zk-hs-2.default.svc.cluster.local:2888:3888 server.3=0.0.0.0:2888:3888
---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs-3
  labels:
    app: zk
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    app: zookeeper-3
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs-3
  labels:
    app: zk
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper-3
